// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcC65rkPS36MK5N4BZoq46y1SvuK9Loko',
    appId: '1:711425644216:web:d89202adad5f273d33064d',
    messagingSenderId: '711425644216',
    projectId: 'maed-delivery-3f3c6',
    authDomain: 'maed-delivery-3f3c6.firebaseapp.com',
    storageBucket: 'maed-delivery-3f3c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfKNzg1gKVfcyFjLv1cj2k_2yU2_bJWbY',
    appId: '1:711425644216:android:04e51cca4b652fbe33064d',
    messagingSenderId: '711425644216',
    projectId: 'maed-delivery-3f3c6',
    storageBucket: 'maed-delivery-3f3c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_nrjXvyAmc4bZ_z8LjegJGCCTAannX3o',
    appId: '1:711425644216:ios:db724d77a392590033064d',
    messagingSenderId: '711425644216',
    projectId: 'maed-delivery-3f3c6',
    storageBucket: 'maed-delivery-3f3c6.firebasestorage.app',
    iosBundleId: 'com.example.foodPrimeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_nrjXvyAmc4bZ_z8LjegJGCCTAannX3o',
    appId: '1:711425644216:ios:db724d77a392590033064d',
    messagingSenderId: '711425644216',
    projectId: 'maed-delivery-3f3c6',
    storageBucket: 'maed-delivery-3f3c6.firebasestorage.app',
    iosBundleId: 'com.example.foodPrimeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcC65rkPS36MK5N4BZoq46y1SvuK9Loko',
    appId: '1:711425644216:web:6ffad99f99e5ce4733064d',
    messagingSenderId: '711425644216',
    projectId: 'maed-delivery-3f3c6',
    authDomain: 'maed-delivery-3f3c6.firebaseapp.com',
    storageBucket: 'maed-delivery-3f3c6.firebasestorage.app',
  );
}
